### ISSUE TITLE
actually not an issue

### ISSUE THREAD

**Issue by suggested-username** [xdmingo/card-switcher#1]
1. your discord not work
2. how to add secondary effect according to the dungeon?

**Comment by xdmingo** [comment]
The module will pick the secondary effect for you. You just have to set the basic secondary effect incase the boss doesnt have any specific type.

**Comment by suggested-username** [comment]
hell o again. your card switcher sets the "Floristry Commission" as the default effect, which is okay since it gives 3500 magic and phys ampli. but I want the following effects as the secondary effects rather than the default "Piscivore"

1. Azart Special Officer on Azart type dungeons --> 2000 Phys/Magi ampli and some crits
![image](https://user-images.githubusercontent.com/55346409/114367249-75e8ce80-9ba6-11eb-9247-d03119059182.png)

2. Diabolical on Demon type dungeons ---> same as above
![image](https://user-images.githubusercontent.com/55346409/114367484-ae88a800-9ba6-11eb-9f8b-5b67df37a4bd.png)

and many more. long story short, maybe you should edit your secondary effects
